<form
  action="admin/refueling"
  method="POST"
  class="needs-validation modal-content"
  novalidate="novalidate"
  enctype="multipart/form-data"
  onsubmit="submitFormAxios(event)"
>
  <input
    type="hidden"
    name="_token"
    value="AQNLvAb467g0eZtkGATqrKcNNVohCNfvLiX4IjQc"
    autocomplete="off"
  />
  <div class="card-header my-3 p-2 border-bottom">
    <h4>Refueling List</h4>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-md-12 col-lg-6">
        <div class="form-group row my-2">
          <label for="vehicle" class="col-sm-5 col-form-label"
            >Vehicle <i class="text-danger">*</i></label
          >
          <div class="col-sm-7">
            <select
              class="form-control basic-single"
              required
              name="vehicle_id"
              id="vehicle"
              data-select2-id="vehicle"
              tabindex="-1"
              aria-hidden="true"
            >
              <option value="" selected="selected">Please select one</option>
              <option value="1">Suzuki-80937</option>
              <option value="2">Mazda-88814</option>
              <option value="3">Cadillac-95769</option>
              <option value="4">Cadillac-32003</option>
              <option value="5">Buick-14376</option>
              <option value="6">Porsche-12325</option>
              <option value="7">Lexus-49180</option>
              <option value="8">Infiniti-46968</option>
              <option value="9">Audi-80686</option>
              <option value="10">Buick-83145</option>
              <option value="11">Lexus-18180</option>
              <option value="12">Hyundai-18578</option>
              <option value="13">BMW-58390</option>
              <option value="14">Honda-46662</option>
              <option value="15">Mazda-38501</option>
              <option value="16">Volvo-16980</option>
              <option value="17">Mercedes-Benz-40892</option>
              <option value="18">Mercedes-Benz-23570</option>
              <option value="19">Buick-40799</option>
              <option value="20">Mercedes-Benz-83084</option>
              <option value="21">Land Rover-77623</option>
              <option value="22">Volkswagen-21130</option>
              <option value="23">Mazda-63442</option>
              <option value="24">Acura-89561</option>
              <option value="25">Chevrolet-94588</option>
              <option value="26">Jaguar-72591</option>
              <option value="27">Acura-48260</option>
              <option value="28">Mercedes-Benz-90642</option>
              <option value="29">Volkswagen-90043</option>
              <option value="30">Kia-78312</option>
              <option value="31">Acura-49322</option>
              <option value="32">Audi-65731</option>
              <option value="33">Volvo-94517</option>
              <option value="34">Acura-32293</option>
              <option value="35">Chevrolet-96601</option>
              <option value="36">Nissan-93981</option>
              <option value="37">Land Rover-77758</option>
              <option value="38">Volkswagen-68445</option>
              <option value="39">Jaguar-86573</option>
              <option value="40">Chevrolet-68537</option>
              <option value="41">Honda-50607</option>
              <option value="42">Buick-41864</option>
              <option value="43">Volvo-44451</option>
              <option value="44">Land Rover-91753</option>
              <option value="45">Infiniti-80976</option>
              <option value="46">Hyundai-32083</option>
              <option value="47">Nissan-16587</option>
              <option value="48">Nissan-64686</option>
              <option value="49">Jaguar-64131</option>
              <option value="50">Porsche-91865</option>
              <option value="51">Kia-38976</option>
              <option value="52">Chevrolet-84153</option>
              <option value="53">Volkswagen-61079</option>
              <option value="54">Mercedes-Benz-41056</option>
              <option value="55">Acura-52059</option>
              <option value="56">Acura-45666</option>
              <option value="57">Ford-99244</option>
              <option value="58">BMW-30366</option>
              <option value="59">Chevrolet-44067</option>
              <option value="60">Jaguar-72774</option>
              <option value="61">Nissan-74884</option>
              <option value="62">Land Rover-70776</option>
              <option value="63">Volvo-36474</option>
              <option value="64">Mazda-38497</option>
              <option value="65">BMW-54325</option>
              <option value="66">Porsche-75139</option>
              <option value="67">Mercedes-Benz-16772</option>
              <option value="68">Land Rover-30805</option>
              <option value="69">Lexus-56451</option>
              <option value="70">Nissan-65529</option>
              <option value="71">Volkswagen-89678</option>
              <option value="72">Land Rover-72858</option>
              <option value="73">Lexus-43494</option>
              <option value="74">Buick-51804</option>
              <option value="75">Chevrolet-10070</option>
              <option value="76">Toyota-65031</option>
              <option value="77">Mazda-52780</option>
              <option value="78">Porsche-36557</option>
              <option value="79">Ford-47644</option>
              <option value="80">Honda-19661</option>
              <option value="81">Lexus-94482</option>
              <option value="82">Suzuki-73538</option>
              <option value="83">Porsche-14746</option>
              <option value="84">Volvo-89130</option>
              <option value="85">Mazda-35869</option>
              <option value="86">Nissan-42579</option>
              <option value="87">Acura-51010</option>
              <option value="88">Mercedes-Benz-88451</option>
              <option value="89">Suzuki-73467</option>
              <option value="90">BMW-91777</option>
              <option value="91">Land Rover-62611</option>
              <option value="92">Kia-95249</option>
              <option value="93">Lexus-99365</option>
              <option value="94">Toyota-96949</option>
              <option value="95">Acura-95442</option>
              <option value="96">Infiniti-47594</option>
              <option value="97">Audi-82727</option>
              <option value="98">Nissan-43727</option>
              <option value="99">Jaguar-19277</option>
              <option value="100">Mazda-90610</option>
              <option value="101">Kia-48884</option>
              <option value="102">Porsche-32177</option>
              <option value="103">Audi-30444</option>
              <option value="104">Kia-79198</option>
              <option value="105">Honda-80566</option>
              <option value="106">Infiniti-67525</option>
              <option value="107">Cadillac-77072</option>
              <option value="108">Chevrolet-74727</option>
              <option value="109">Hyundai-50990</option>
              <option value="110">Mercedes-Benz-19651</option>
              <option value="111">Audi-15258</option>
              <option value="112">Volvo-84672</option>
              <option value="113">Ford-86449</option>
              <option value="114">Nissan-42920</option>
              <option value="115">Cadillac-45876</option>
              <option value="116">BMW-74172</option>
              <option value="117">Audi-43901</option>
              <option value="118">Mercedes-Benz-32092</option>
              <option value="119">Honda-32368</option>
              <option value="120">Audi-45330</option>
              <option value="121">Mazda-29099</option>
              <option value="122">Volkswagen-17891</option>
              <option value="123">Jaguar-28689</option>
              <option value="124">Acura-32003</option>
              <option value="125">Volkswagen-69350</option>
              <option value="126">Audi-83174</option>
              <option value="127">Suzuki-92323</option>
              <option value="128">Volkswagen-50971</option>
              <option value="129">Suzuki-95621</option>
              <option value="130">Suzuki-66711</option>
              <option value="131">Acura-55906</option>
              <option value="132">Infiniti-69966</option>
              <option value="133">Nissan-35114</option>
              <option value="134">Buick-79904</option>
              <option value="135">Buick-72372</option>
              <option value="136">Nissan-37407</option>
              <option value="137">Nissan-95293</option>
              <option value="138">Volvo-21754</option>
              <option value="139">Jaguar-86604</option>
              <option value="140">Mercedes-Benz-64242</option>
              <option value="141">Hyundai-98476</option>
              <option value="142">Suzuki-75868</option>
              <option value="143">Land Rover-85338</option>
              <option value="144">Hyundai-86978</option>
              <option value="145">BMW-39997</option>
              <option value="146">Acura-72835</option>
              <option value="147">BMW-54778</option>
              <option value="148">Mazda-56253</option>
              <option value="149">Audi-63619</option>
              <option value="150">Porsche-25655</option>
              <option value="151">Mazda-74798</option>
              <option value="152">Nissan-68764</option>
              <option value="153">Honda-32354</option>
              <option value="154">Chevrolet-41536</option>
              <option value="155">Hyundai-10207</option>
              <option value="156">Mazda-98581</option>
              <option value="157">Ford-94400</option>
              <option value="158">Volvo-79019</option>
              <option value="159">Audi-98803</option>
              <option value="160">Cadillac-89126</option>
              <option value="161">Buick-63210</option>
              <option value="162">Cadillac-31508</option>
              <option value="163">Volvo-60748</option>
              <option value="164">Ford-16472</option>
              <option value="165">Chevrolet-17826</option>
              <option value="166">Hyundai-22162</option>
              <option value="167">Mazda-12053</option>
              <option value="168">Kia-85671</option>
              <option value="169">Volvo-19751</option>
              <option value="170">BMW-59591</option>
              <option value="171">Chevrolet-93446</option>
              <option value="172">Kia-69199</option>
              <option value="173">Jaguar-17393</option>
              <option value="174">Lexus-11081</option>
              <option value="175">Toyota-77311</option>
              <option value="176">Honda-35147</option>
              <option value="177">Buick-58505</option>
              <option value="178">Jaguar-29778</option>
              <option value="179">Infiniti-66128</option>
              <option value="180">Buick-42857</option>
              <option value="181">Toyota-26203</option>
              <option value="182">Infiniti-82372</option>
              <option value="183">Kia-70849</option>
              <option value="184">Volvo-12884</option>
              <option value="185">Chevrolet-75983</option>
              <option value="186">Mazda-16390</option>
              <option value="187">Porsche-52790</option>
              <option value="188">Volkswagen-70957</option>
              <option value="189">Volkswagen-77150</option>
              <option value="190">Toyota-48374</option>
              <option value="191">Kia-26580</option>
              <option value="192">Land Rover-47542</option>
              <option value="193">Lexus-14120</option>
              <option value="194">Land Rover-29915</option>
              <option value="195">Volkswagen-59646</option>
              <option value="196">Volkswagen-69620</option>
              <option value="197">Buick-33198</option>
              <option value="198">Land Rover-86385</option>
              <option value="199">Toyota-64190</option>
              <option value="200">BMW-75462</option>
              <option value="201">Toyota-67286</option>
              <option value="202">Mazda-29605</option>
              <option value="203">Acura-49622</option>
              <option value="204">Mazda-39619</option>
              <option value="205">Lexus-32143</option>
              <option value="206">Audi-29961</option>
              <option value="207">Mercedes-Benz-96736</option>
              <option value="208">Kia-75708</option>
              <option value="209">Cadillac-40975</option>
              <option value="210">Lexus-33469</option>
              <option value="211">Jaguar-45514</option>
              <option value="212">Land Rover-94694</option>
              <option value="213">Mazda-94748</option>
              <option value="214">Porsche-14597</option>
              <option value="215">Land Rover-96529</option>
              <option value="216">Infiniti-42839</option>
              <option value="217">Mercedes-Benz-66326</option>
              <option value="218">Kia-15058</option>
              <option value="219">Volkswagen-12079</option>
              <option value="220">Ford-51204</option>
              <option value="221">Porsche-90766</option>
              <option value="222">Hyundai-62401</option>
              <option value="223">Honda-93014</option>
              <option value="224">BMW-84434</option>
              <option value="225">Jaguar-11336</option>
              <option value="226">Volvo-31714</option>
              <option value="227">Lexus-65975</option>
              <option value="228">Chevrolet-83011</option>
              <option value="229">Chevrolet-42754</option>
              <option value="230">Hyundai-62213</option>
              <option value="231">Chevrolet-79032</option>
              <option value="232">Volkswagen-35649</option>
              <option value="233">Audi-65998</option>
              <option value="234">Audi-88702</option>
              <option value="235">Mercedes-Benz-74842</option>
              <option value="236">Mazda-82188</option>
              <option value="237">Honda-28327</option>
              <option value="238">Jaguar-38810</option>
              <option value="239">Land Rover-60523</option>
              <option value="240">Ford-40408</option>
              <option value="241">Mercedes-Benz-94042</option>
              <option value="242">Infiniti-40465</option>
              <option value="243">Kia-42071</option>
              <option value="244">Nissan-37679</option>
              <option value="245">Mazda-85881</option>
              <option value="246">Audi-69881</option>
              <option value="247">Nissan-70848</option>
              <option value="248">Lexus-75918</option>
              <option value="249">Nissan-30641</option>
              <option value="250">BMW-42569</option>
              <option value="251">Toyota-65214</option>
              <option value="252">BMW-90102</option>
              <option value="253">Nissan-90577</option>
              <option value="254">Volkswagen-91232</option>
              <option value="255">Kia-88140</option>
              <option value="256">Toyota-21089</option>
              <option value="257">Ford-92924</option>
              <option value="258">Buick-14007</option>
              <option value="259">Acura-22397</option>
              <option value="260">Chevrolet-98462</option>
              <option value="261">Nissan-43928</option>
              <option value="262">Hyundai-71446</option>
              <option value="263">Toyota-72134</option>
              <option value="264">Acura-54983</option>
              <option value="265">Audi-78451</option>
              <option value="266">Volvo-85007</option>
              <option value="267">Audi-13927</option>
              <option value="268">Land Rover-45993</option>
              <option value="269">Porsche-88885</option>
              <option value="270">Chevrolet-55809</option>
              <option value="271">Porsche-58536</option>
              <option value="272">Mercedes-Benz-60893</option>
              <option value="273">Nissan-66934</option>
              <option value="274">Volvo-33513</option>
              <option value="275">BMW-65121</option>
              <option value="276">Hyundai-16118</option>
              <option value="277">Buick-64803</option>
              <option value="278">Volkswagen-10500</option>
              <option value="279">BMW-86659</option>
              <option value="280">Toyota-13346</option>
              <option value="281">Acura-98367</option>
              <option value="282">Honda-88784</option>
              <option value="283">Jaguar-23222</option>
              <option value="284">Land Rover-66357</option>
              <option value="285">Mazda-99086</option>
              <option value="286">Acura-47590</option>
              <option value="287">Nissan-28818</option>
              <option value="288">Volvo-26690</option>
              <option value="289">Ford-47635</option>
              <option value="290">Mercedes-Benz-99392</option>
              <option value="291">Mercedes-Benz-42357</option>
              <option value="292">Acura-91131</option>
              <option value="293">Hyundai-10353</option>
              <option value="294">Chevrolet-59783</option>
              <option value="295">Cadillac-69615</option>
              <option value="296">Kia-11223</option>
              <option value="297">Volkswagen-74353</option>
              <option value="298">Cadillac-88617</option>
              <option value="299">Mazda-55550</option>
              <option value="300">Suzuki-29295</option>
              <option value="301">BMW-32146</option>
              <option value="302">Suzuki-85966</option>
              <option value="303">Hyundai-89128</option>
              <option value="304">Infiniti-91083</option>
              <option value="305">Hyundai-79752</option>
              <option value="306">Hyundai-23172</option>
              <option value="307">Mercedes-Benz-36954</option>
              <option value="308">Honda-22626</option>
              <option value="309">Lexus-10979</option>
              <option value="310">Suzuki-91842</option>
              <option value="311">Lexus-16703</option>
              <option value="312">Nissan-86449</option>
              <option value="313">Ford-14546</option>
              <option value="314">Ford-94338</option>
              <option value="315">Infiniti-29044</option>
              <option value="316">Land Rover-21509</option>
              <option value="317">Honda-40381</option>
              <option value="318">Suzuki-15799</option>
              <option value="319">Chevrolet-46225</option>
              <option value="320">Suzuki-88527</option>
              <option value="321">Jaguar-88067</option>
              <option value="322">Toyota-18096</option>
              <option value="323">Porsche-79445</option>
              <option value="324">Infiniti-37365</option>
              <option value="325">Buick-54287</option>
              <option value="326">Ford-83375</option>
              <option value="327">Buick-47012</option>
              <option value="328">Jaguar-59409</option>
              <option value="329">Buick-59281</option>
              <option value="330">Jaguar-90426</option>
              <option value="331">Mazda-48293</option>
              <option value="332">Chevrolet-77869</option>
              <option value="333">Buick-76381</option>
              <option value="334">BMW-96138</option>
              <option value="335">Nissan-49376</option>
              <option value="336">Volvo-92432</option>
              <option value="337">Hyundai-29062</option>
              <option value="338">Cadillac-99497</option>
              <option value="339">Cadillac-10067</option>
              <option value="340">Infiniti-83007</option>
              <option value="341">Mazda-36589</option>
              <option value="342">Lexus-43969</option>
              <option value="343">Ford-23331</option>
              <option value="344">Nissan-39416</option>
              <option value="345">Infiniti-14685</option>
              <option value="346">Toyota-38884</option>
              <option value="347">Honda-70582</option>
              <option value="348">Lexus-27484</option>
              <option value="349">Kia-96828</option>
              <option value="350">Hyundai-37920</option>
              <option value="351">Nissan-38120</option>
              <option value="352">Volkswagen-91209</option>
              <option value="353">Audi-85518</option>
              <option value="354">Porsche-33763</option>
              <option value="355">Kia-47141</option>
              <option value="356">Ford-29160</option>
              <option value="357">Suzuki-52334</option>
              <option value="358">Honda-76437</option>
              <option value="359">Lexus-72121</option>
              <option value="360">Mazda-73826</option>
              <option value="361">Hyundai-56072</option>
              <option value="362">Kia-48267</option>
              <option value="363">Land Rover-75652</option>
              <option value="364">Lexus-39083</option>
              <option value="365">Chevrolet-77663</option>
              <option value="366">Mazda-49802</option>
              <option value="367">Hyundai-20978</option>
              <option value="368">Nissan-56605</option>
              <option value="369">Nissan-33333</option>
              <option value="370">Volvo-13078</option>
              <option value="371">Land Rover-77536</option>
              <option value="372">Land Rover-87894</option>
              <option value="373">Infiniti-97228</option>
              <option value="374">Acura-76634</option>
              <option value="375">Hyundai-51889</option>
              <option value="376">Kia-85494</option>
              <option value="377">Volkswagen-41539</option>
              <option value="378">Acura-12287</option>
              <option value="379">Mercedes-Benz-57104</option>
              <option value="380">Honda-13310</option>
              <option value="381">Acura-24441</option>
              <option value="382">BMW-22298</option>
              <option value="383">Mercedes-Benz-45591</option>
              <option value="384">Jaguar-54684</option>
              <option value="385">BMW-91513</option>
              <option value="386">Mercedes-Benz-20405</option>
              <option value="387">Buick-48958</option>
              <option value="388">Hyundai-50632</option>
              <option value="389">Mazda-61846</option>
              <option value="390">Volkswagen-88834</option>
              <option value="391">Ford-69503</option>
              <option value="392">Nissan-72132</option>
              <option value="393">Volvo-46690</option>
              <option value="394">Mazda-77522</option>
              <option value="395">Jaguar-62410</option>
              <option value="396">Acura-71053</option>
              <option value="397">Porsche-58034</option>
              <option value="398">Mazda-57675</option>
              <option value="399">Volvo-15661</option>
              <option value="400">Nissan-89179</option>
              <option value="401">Acura-33469</option>
              <option value="402">Nissan-32104</option>
              <option value="403">Suzuki-77905</option>
              <option value="404">Volkswagen-66905</option>
              <option value="405">Toyota-60028</option>
              <option value="406">Volkswagen-78367</option>
              <option value="407">Hyundai-42568</option>
              <option value="408">Honda-38761</option>
              <option value="409">Mazda-46876</option>
              <option value="410">Suzuki-13133</option>
              <option value="411">Mazda-52792</option>
              <option value="412">Chevrolet-63433</option>
              <option value="413">Hyundai-59040</option>
              <option value="414">Hyundai-78465</option>
              <option value="415">Land Rover-54484</option>
              <option value="416">Mazda-69439</option>
              <option value="417">Toyota-44515</option>
              <option value="418">Acura-21208</option>
              <option value="419">Infiniti-65954</option>
              <option value="420">Infiniti-42455</option>
              <option value="421">Audi-99058</option>
              <option value="422">Buick-98393</option>
              <option value="423">BMW-12280</option>
              <option value="424">Volvo-99852</option>
              <option value="425">BMW-92489</option>
              <option value="426">Chevrolet-30716</option>
              <option value="427">Toyota-91348</option>
              <option value="428">Ford-39624</option>
              <option value="429">Lexus-64628</option>
              <option value="430">Ford-72414</option>
              <option value="431">Ford-20258</option>
              <option value="432">Mazda-58847</option>
              <option value="433">Ford-86772</option>
              <option value="434">Infiniti-96355</option>
              <option value="435">Acura-65688</option>
              <option value="436">Mazda-47943</option>
              <option value="437">Acura-52519</option>
              <option value="438">Suzuki-61391</option>
              <option value="439">Buick-44008</option>
              <option value="440">Chevrolet-25929</option>
              <option value="441">Volkswagen-98239</option>
              <option value="442">Buick-92712</option>
              <option value="443">Nissan-61103</option>
              <option value="444">Infiniti-32862</option>
              <option value="445">Jaguar-27309</option>
              <option value="446">Chevrolet-70867</option>
              <option value="447">Ford-40164</option>
              <option value="448">Buick-16147</option>
              <option value="449">Mazda-52971</option>
              <option value="450">Mercedes-Benz-87916</option>
              <option value="451">Jaguar-24933</option>
              <option value="452">Kia-84574</option>
              <option value="453">Lexus-64887</option>
              <option value="454">Porsche-84528</option>
              <option value="455">Mazda-10820</option>
              <option value="456">Land Rover-50355</option>
              <option value="457">Hyundai-46926</option>
              <option value="458">Buick-38043</option>
              <option value="459">Mazda-20484</option>
              <option value="460">Infiniti-16320</option>
              <option value="461">Land Rover-83338</option>
              <option value="462">Nissan-17045</option>
              <option value="463">Infiniti-64649</option>
              <option value="464">Cadillac-90446</option>
              <option value="465">Buick-36869</option>
              <option value="466">Ford-98386</option>
              <option value="467">Acura-51165</option>
              <option value="468">Honda-10723</option>
              <option value="469">Chevrolet-65110</option>
              <option value="470">Nissan-80809</option>
              <option value="471">Suzuki-59419</option>
              <option value="472">Audi-57170</option>
              <option value="473">Acura-40673</option>
              <option value="474">Honda-75562</option>
              <option value="475">Acura-81132</option>
              <option value="476">Cadillac-98835</option>
              <option value="477">Toyota-92447</option>
              <option value="478">Hyundai-26895</option>
              <option value="479">Infiniti-58508</option>
              <option value="480">Porsche-65160</option>
              <option value="481">Kia-38291</option>
              <option value="482">Hyundai-68459</option>
              <option value="483">Volkswagen-40311</option>
              <option value="484">Volkswagen-58420</option>
              <option value="485">Suzuki-59999</option>
              <option value="486">Lexus-71630</option>
              <option value="487">Mazda-52002</option>
              <option value="488">Volkswagen-74008</option>
              <option value="489">Infiniti-22745</option>
              <option value="490">Volvo-24855</option>
              <option value="491">Land Rover-51383</option>
              <option value="492">BMW-35908</option>
              <option value="493">Chevrolet-71859</option>
              <option value="494">Ford-57378</option>
              <option value="495">Porsche-93795</option>
              <option value="496">Kia-52271</option>
              <option value="497">Land Rover-87727</option>
              <option value="498">Volkswagen-53370</option>
              <option value="499">Jaguar-54491</option>
              <option value="500">Volvo-90474</option>
              <option value="501">Porsche-51809</option>
              <option value="502">Toyota-88990</option>
              <option value="503">Buick-73108</option>
              <option value="504">Lexus-18166</option>
              <option value="505">Jaguar-81845</option>
              <option value="506">Acura-36541</option>
              <option value="507">Hyundai-18685</option>
              <option value="508">Honda-62064</option>
              <option value="509">Ford-70140</option>
              <option value="510">Honda-11407</option>
              <option value="511">Volkswagen-19825</option>
              <option value="512">Mazda-40828</option>
              <option value="513">Land Rover-19970</option>
              <option value="514">Mercedes-Benz-49526</option>
              <option value="515">Audi-97384</option>
              <option value="516">Audi-39753</option>
              <option value="517">Infiniti-33695</option>
              <option value="518">Honda-96337</option>
              <option value="519">Infiniti-41741</option>
              <option value="520">Buick-96188</option>
              <option value="521">Porsche-25723</option>
              <option value="522">Acura-38683</option>
              <option value="523">Chevrolet-40600</option>
              <option value="524">Suzuki-94645</option>
              <option value="525">Mazda-25031</option>
              <option value="526">Ford-46673</option>
              <option value="527">Honda-57395</option>
              <option value="528">Land Rover-13271</option>
              <option value="529">Mercedes-Benz-41149</option>
              <option value="530">Infiniti-87937</option>
              <option value="531">Mazda-91091</option>
              <option value="532">Honda-36305</option>
              <option value="533">Mercedes-Benz-83238</option>
              <option value="534">Volvo-37913</option>
              <option value="535">Kia-77497</option>
              <option value="536">BMW-36208</option>
              <option value="537">Chevrolet-53924</option>
              <option value="538">Chevrolet-47175</option>
              <option value="539">Ford-96531</option>
              <option value="540">Audi-61219</option>
              <option value="541">Jaguar-72402</option>
              <option value="542">Chevrolet-81120</option>
              <option value="543">BMW-97823</option>
              <option value="544">BMW-87599</option>
              <option value="545">Buick-41317</option>
              <option value="546">Nissan-70657</option>
              <option value="547">Hyundai-74261</option>
              <option value="548">Audi-49611</option>
              <option value="549">Hyundai-60586</option>
              <option value="550">Ford-43375</option>
              <option value="551">Kia-39333</option>
              <option value="552">Infiniti-60675</option>
              <option value="553">Ford-72795</option>
              <option value="554">Land Rover-69181</option>
              <option value="555">Mazda-53239</option>
              <option value="556">Infiniti-75438</option>
              <option value="557">Infiniti-14401</option>
              <option value="558">Land Rover-56857</option>
              <option value="559">Acura-36344</option>
              <option value="560">Hyundai-51911</option>
              <option value="561">Kia-15666</option>
              <option value="562">Kia-29469</option>
              <option value="563">Porsche-35861</option>
              <option value="564">Suzuki-20192</option>
              <option value="565">Hyundai-41484</option>
              <option value="566">Cadillac-48663</option>
              <option value="567">Ford-40306</option>
              <option value="568">Porsche-99247</option>
              <option value="569">Lexus-77904</option>
              <option value="570">Infiniti-73471</option>
              <option value="571">Lexus-57179</option>
              <option value="572">Acura-81766</option>
              <option value="573">Porsche-50097</option>
              <option value="574">Ford-17527</option>
              <option value="575">Jaguar-37720</option>
              <option value="576">Suzuki-33793</option>
              <option value="577">Kia-60193</option>
              <option value="578">Chevrolet-86331</option>
              <option value="579">Lexus-12619</option>
              <option value="580">Mercedes-Benz-62904</option>
              <option value="581">Toyota-80720</option>
              <option value="582">Land Rover-62355</option>
              <option value="583">Nissan-83199</option>
              <option value="584">Land Rover-29377</option>
              <option value="585">Suzuki-94997</option>
              <option value="586">Mazda-91193</option>
              <option value="587">Infiniti-84739</option>
              <option value="588">Ford-49754</option>
              <option value="589">Mazda-56172</option>
              <option value="590">Volvo-27169</option>
              <option value="591">Chevrolet-18902</option>
              <option value="592">Toyota-41205</option>
              <option value="593">Acura-99822</option>
              <option value="594">Acura-23706</option>
              <option value="595">Infiniti-39783</option>
              <option value="596">Porsche-65570</option>
              <option value="597">Land Rover-13992</option>
              <option value="598">Volkswagen-61090</option>
              <option value="599">Infiniti-39233</option>
              <option value="600">Mercedes-Benz-88619</option>
              <option value="601">Hyundai-58333</option>
              <option value="602">Jaguar-29775</option>
              <option value="603">Toyota-65914</option>
              <option value="604">Jaguar-33117</option>
              <option value="605">Hyundai-35979</option>
              <option value="606">Volvo-94478</option>
              <option value="607">Buick-13477</option>
              <option value="608">Nissan-77460</option>
              <option value="609">Suzuki-73234</option>
              <option value="610">Buick-79347</option>
              <option value="611">Land Rover-25273</option>
              <option value="612">Kia-58211</option>
              <option value="613">Volkswagen-88764</option>
              <option value="614">Honda-90250</option>
              <option value="615">Suzuki-23977</option>
              <option value="616">Mazda-95285</option>
              <option value="617">Acura-49524</option>
              <option value="618">Kia-81224</option>
              <option value="619">BMW-59153</option>
              <option value="620">Hyundai-35622</option>
              <option value="621">Porsche-48937</option>
              <option value="622">Honda-26916</option>
              <option value="623">Mazda-90735</option>
              <option value="624">Nissan-18495</option>
              <option value="625">Jaguar-82651</option>
              <option value="626">Volvo-12791</option>
              <option value="627">Buick-39043</option>
              <option value="628">Audi-86505</option>
              <option value="629">Ford-85609</option>
              <option value="630">Hyundai-24376</option>
              <option value="631">Toyota-31613</option>
              <option value="632">Mercedes-Benz-26356</option>
              <option value="633">Toyota-81409</option>
              <option value="634">Volvo-55497</option>
              <option value="635">Jaguar-36949</option>
              <option value="636">Nissan-16940</option>
              <option value="637">Buick-77464</option>
              <option value="638">Acura-15771</option>
              <option value="639">BMW-25285</option>
              <option value="640">Jaguar-89998</option>
              <option value="641">Volvo-55665</option>
              <option value="642">Toyota-75584</option>
              <option value="643">Ford-90202</option>
              <option value="644">Hyundai-53122</option>
              <option value="645">BMW-86440</option>
              <option value="646">Honda-58493</option>
              <option value="647">Mazda-30829</option>
              <option value="648">Cadillac-28732</option>
              <option value="649">Jaguar-30583</option>
              <option value="650">Volkswagen-93275</option>
              <option value="651">Toyota-68583</option>
              <option value="652">Volkswagen-45901</option>
              <option value="653">Chevrolet-39661</option>
              <option value="654">Hyundai-47878</option>
              <option value="655">Buick-92066</option>
              <option value="656">Buick-46466</option>
              <option value="657">BMW-94046</option>
              <option value="658">Infiniti-11012</option>
              <option value="659">BMW-66851</option>
              <option value="660">Nissan-66617</option>
              <option value="661">Ford-86360</option>
              <option value="662">Volkswagen-65984</option>
              <option value="663">Volvo-39158</option>
              <option value="664">Acura-35091</option>
              <option value="665">Land Rover-89280</option>
              <option value="666">Porsche-29497</option>
              <option value="667">Volkswagen-51936</option>
              <option value="668">Kia-73014</option>
              <option value="669">Hyundai-75357</option>
              <option value="670">Volvo-95264</option>
              <option value="671">Hyundai-24887</option>
              <option value="672">Buick-78625</option>
              <option value="673">Suzuki-86713</option>
              <option value="674">Mazda-49658</option>
              <option value="675">BMW-35297</option>
              <option value="676">Lexus-94141</option>
              <option value="677">Toyota-54667</option>
              <option value="678">Jaguar-85992</option>
              <option value="679">Kia-89972</option>
              <option value="680">Volkswagen-46630</option>
              <option value="681">Porsche-52412</option>
              <option value="682">Buick-39242</option>
              <option value="683">Porsche-95586</option>
              <option value="684">Mercedes-Benz-61344</option>
              <option value="685">Hyundai-26896</option>
              <option value="686">Jaguar-99352</option>
              <option value="687">Cadillac-51140</option>
              <option value="688">Kia-68484</option>
              <option value="689">Porsche-46517</option>
              <option value="690">Cadillac-46251</option>
              <option value="691">Suzuki-52716</option>
              <option value="692">Nissan-29754</option>
              <option value="693">Hyundai-45729</option>
              <option value="694">Honda-85396</option>
              <option value="695">Volkswagen-97666</option>
              <option value="696">Mercedes-Benz-41603</option>
              <option value="697">Mazda-99081</option>
              <option value="698">Honda-10346</option>
              <option value="699">Chevrolet-20605</option>
              <option value="700">Honda-37887</option>
              <option value="701">Buick-13825</option>
              <option value="702">Toyota-68791</option>
              <option value="703">Acura-12863</option>
              <option value="704">Hyundai-61297</option>
              <option value="705">Hyundai-82676</option>
              <option value="706">Volvo-64690</option>
              <option value="707">Lexus-36973</option>
              <option value="708">Ford-46714</option>
              <option value="709">Infiniti-67732</option>
              <option value="710">Honda-26650</option>
              <option value="711">Buick-42457</option>
              <option value="712">Ford-81916</option>
              <option value="713">Land Rover-66795</option>
              <option value="714">Nissan-12876</option>
              <option value="715">Hyundai-87647</option>
              <option value="716">Lexus-42436</option>
              <option value="717">Acura-86789</option>
              <option value="718">Infiniti-82951</option>
              <option value="719">Jaguar-27365</option>
              <option value="720">BMW-81207</option>
              <option value="721">Ford-51444</option>
              <option value="722">Mazda-67557</option>
              <option value="723">Ford-77463</option>
              <option value="724">Buick-82189</option>
              <option value="725">Acura-53152</option>
              <option value="726">Toyota-19781</option>
              <option value="727">Volkswagen-57147</option>
              <option value="728">Jaguar-55391</option>
              <option value="729">Acura-89642</option>
              <option value="730">Infiniti-68758</option>
              <option value="731">Nissan-92678</option>
              <option value="732">Hyundai-17344</option>
              <option value="733">Volkswagen-59900</option>
              <option value="734">Audi-68460</option>
              <option value="735">Chevrolet-68559</option>
              <option value="736">Suzuki-30239</option>
              <option value="737">Nissan-34318</option>
              <option value="738">Hyundai-90261</option>
              <option value="739">Porsche-82022</option>
              <option value="740">Buick-14722</option>
              <option value="741">Infiniti-32377</option>
              <option value="742">Land Rover-42404</option>
              <option value="743">Mercedes-Benz-31821</option>
              <option value="744">Suzuki-61210</option>
              <option value="745">Ford-52699</option>
              <option value="746">Nissan-73342</option>
              <option value="747">Hyundai-34146</option>
              <option value="748">Chevrolet-18345</option>
              <option value="749">Suzuki-72094</option>
              <option value="750">Land Rover-40911</option>
              <option value="751">Infiniti-82139</option>
              <option value="752">Kia-21289</option>
              <option value="753">Chevrolet-10771</option>
              <option value="754">Volkswagen-21668</option>
              <option value="755">Jaguar-31357</option>
              <option value="756">Volkswagen-78530</option>
              <option value="757">Audi-92006</option>
              <option value="758">Kia-57124</option>
              <option value="759">Cadillac-73613</option>
              <option value="760">Infiniti-76020</option>
              <option value="761">Buick-66806</option>
              <option value="762">Jaguar-87983</option>
              <option value="763">Suzuki-64007</option>
              <option value="764">Porsche-20946</option>
              <option value="765">Mazda-29014</option>
              <option value="766">Volkswagen-85555</option>
              <option value="767">Jaguar-64650</option>
              <option value="768">Volvo-25578</option>
              <option value="769">Toyota-44632</option>
              <option value="770">Mazda-35491</option>
              <option value="771">Volvo-14651</option>
              <option value="772">Cadillac-25219</option>
              <option value="773">Chevrolet-93851</option>
              <option value="774">Buick-48875</option>
              <option value="775">Infiniti-25249</option>
              <option value="776">Kia-46028</option>
              <option value="777">Buick-97132</option>
              <option value="778">Nissan-68548</option>
              <option value="779">Land Rover-25555</option>
              <option value="780">Audi-81114</option>
              <option value="781">Volkswagen-23902</option>
              <option value="782">Lexus-49808</option>
              <option value="783">Mazda-78860</option>
              <option value="784">Mercedes-Benz-96534</option>
              <option value="785">Audi-79419</option>
              <option value="786">Chevrolet-54661</option>
              <option value="787">Buick-23283</option>
              <option value="788">Nissan-89481</option>
              <option value="789">Chevrolet-96996</option>
              <option value="790">Acura-62412</option>
              <option value="791">Kia-19988</option>
              <option value="792">Infiniti-20452</option>
              <option value="793">Porsche-36898</option>
              <option value="794">Porsche-53752</option>
              <option value="795">Kia-34233</option>
              <option value="796">Hyundai-65846</option>
              <option value="797">Chevrolet-65551</option>
              <option value="798">Honda-99088</option>
              <option value="799">Acura-32050</option>
              <option value="800">Lexus-42836</option>
              <option value="801">Land Rover-87455</option>
              <option value="802">Toyota-84073</option>
              <option value="803">Hyundai-53386</option>
              <option value="804">Hyundai-94885</option>
              <option value="805">Honda-36216</option>
              <option value="806">Kia-70845</option>
              <option value="807">Chevrolet-97863</option>
              <option value="808">Land Rover-81608</option>
              <option value="809">Volkswagen-98418</option>
              <option value="810">Lexus-61221</option>
              <option value="811">Mercedes-Benz-36568</option>
              <option value="812">Acura-36386</option>
              <option value="813">BMW-39529</option>
              <option value="814">Volvo-83949</option>
              <option value="815">Ford-31901</option>
              <option value="816">Jaguar-18242</option>
              <option value="817">Ford-10440</option>
              <option value="818">Mazda-61008</option>
              <option value="819">Volkswagen-12831</option>
              <option value="820">Infiniti-99307</option>
              <option value="821">Kia-22770</option>
              <option value="822">Hyundai-27830</option>
              <option value="823">Mercedes-Benz-52436</option>
              <option value="824">Porsche-95052</option>
              <option value="825">Volkswagen-35140</option>
              <option value="826">Mazda-84712</option>
              <option value="827">Cadillac-68823</option>
              <option value="828">Honda-56978</option>
              <option value="829">Toyota-77514</option>
              <option value="830">Hyundai-12714</option>
              <option value="831">Porsche-73706</option>
              <option value="832">Buick-27707</option>
              <option value="833">Toyota-92935</option>
              <option value="834">Ford-95346</option>
              <option value="835">Honda-52603</option>
              <option value="836">BMW-51054</option>
              <option value="837">Kia-48180</option>
              <option value="838">Honda-38422</option>
              <option value="839">Mazda-47181</option>
              <option value="840">Porsche-49877</option>
              <option value="841">Lexus-15948</option>
              <option value="842">Infiniti-25332</option>
              <option value="843">Infiniti-92971</option>
              <option value="844">Ford-75811</option>
              <option value="845">Buick-85636</option>
              <option value="846">Land Rover-87442</option>
              <option value="847">Audi-94031</option>
              <option value="848">Ford-66918</option>
              <option value="849">Cadillac-17941</option>
              <option value="850">Hyundai-87727</option>
              <option value="851">Jaguar-23841</option>
              <option value="852">Audi-48300</option>
              <option value="853">Volvo-19780</option>
              <option value="854">Ford-95615</option>
              <option value="855">Acura-47920</option>
              <option value="856">Infiniti-16761</option>
              <option value="857">Hyundai-67108</option>
              <option value="858">Infiniti-47421</option>
              <option value="859">Buick-69264</option>
              <option value="860">Buick-23837</option>
              <option value="861">Mercedes-Benz-65964</option>
              <option value="862">Ford-18086</option>
              <option value="863">Audi-84363</option>
              <option value="864">Mazda-57940</option>
              <option value="865">Volkswagen-37919</option>
              <option value="866">Audi-26701</option>
              <option value="867">Volvo-38705</option>
              <option value="868">Mazda-14484</option>
              <option value="869">Infiniti-31453</option>
              <option value="870">Volvo-91645</option>
              <option value="871">Suzuki-31836</option>
              <option value="872">Mercedes-Benz-51866</option>
              <option value="873">Jaguar-64356</option>
              <option value="874">Acura-39477</option>
              <option value="875">Ford-48034</option>
              <option value="876">Mazda-46838</option>
              <option value="877">Infiniti-60018</option>
              <option value="878">Cadillac-50387</option>
              <option value="879">Cadillac-45862</option>
              <option value="880">BMW-23523</option>
              <option value="881">Jaguar-71921</option>
              <option value="882">Infiniti-15070</option>
              <option value="883">Toyota-49812</option>
              <option value="884">Jaguar-57697</option>
              <option value="885">Hyundai-56915</option>
              <option value="886">Nissan-45097</option>
              <option value="887">Volvo-40008</option>
              <option value="888">Land Rover-57433</option>
              <option value="889">Chevrolet-61881</option>
              <option value="890">Mazda-46769</option>
              <option value="891">Land Rover-36996</option>
              <option value="892">BMW-15804</option>
              <option value="893">Chevrolet-91631</option>
              <option value="894">Mazda-75271</option>
              <option value="895">Hyundai-35654</option>
              <option value="896">Mercedes-Benz-34522</option>
              <option value="897">BMW-98264</option>
              <option value="898">Hyundai-31078</option>
              <option value="899">Land Rover-81101</option>
              <option value="900">Volvo-19059</option>
              <option value="901">Kia-52821</option>
              <option value="902">Porsche-10266</option>
              <option value="903">Volkswagen-16432</option>
              <option value="904">Buick-75405</option>
              <option value="905">BMW-41565</option>
              <option value="906">Volvo-18660</option>
              <option value="907">Jaguar-75676</option>
              <option value="908">Volvo-95068</option>
              <option value="909">Hyundai-39772</option>
              <option value="910">Mazda-41997</option>
              <option value="911">BMW-49210</option>
              <option value="912">BMW-28781</option>
              <option value="913">BMW-63958</option>
              <option value="914">Chevrolet-39666</option>
              <option value="915">Honda-42875</option>
              <option value="916">BMW-65893</option>
              <option value="917">Land Rover-55706</option>
              <option value="918">Acura-30779</option>
              <option value="919">Porsche-22312</option>
              <option value="920">Land Rover-47876</option>
              <option value="921">Jaguar-31848</option>
              <option value="922">Mazda-78607</option>
              <option value="923">Kia-87781</option>
              <option value="924">Jaguar-43917</option>
              <option value="925">Volkswagen-14463</option>
              <option value="926">Suzuki-70251</option>
              <option value="927">Nissan-97114</option>
              <option value="928">Mazda-30504</option>
              <option value="929">BMW-66027</option>
              <option value="930">Audi-82528</option>
              <option value="931">Suzuki-37500</option>
              <option value="932">Acura-47519</option>
              <option value="933">Kia-98848</option>
              <option value="934">Volkswagen-48120</option>
              <option value="935">Volkswagen-23612</option>
              <option value="936">Suzuki-38483</option>
              <option value="937">Ford-22545</option>
              <option value="938">Acura-35754</option>
              <option value="939">Jaguar-34776</option>
              <option value="940">Hyundai-47564</option>
              <option value="941">Chevrolet-57044</option>
              <option value="942">Land Rover-96328</option>
              <option value="943">Honda-42516</option>
              <option value="944">Kia-73899</option>
              <option value="945">Lexus-45858</option>
              <option value="946">Mercedes-Benz-15566</option>
              <option value="947">Honda-65479</option>
              <option value="948">Buick-44582</option>
              <option value="949">Lexus-44798</option>
              <option value="950">Buick-82476</option>
              <option value="951">Chevrolet-91889</option>
              <option value="952">Acura-95277</option>
              <option value="953">Chevrolet-87364</option>
              <option value="954">Ford-77686</option>
              <option value="955">Land Rover-33202</option>
              <option value="956">Porsche-57919</option>
              <option value="957">Ford-92125</option>
              <option value="958">Kia-55157</option>
              <option value="959">Hyundai-81576</option>
              <option value="960">Cadillac-81232</option>
              <option value="961">Suzuki-40729</option>
              <option value="962">Suzuki-11655</option>
              <option value="963">Audi-99227</option>
              <option value="964">Buick-81501</option>
              <option value="965">Infiniti-74432</option>
              <option value="966">BMW-76101</option>
              <option value="967">Buick-30452</option>
              <option value="968">Volvo-30300</option>
              <option value="969">Toyota-22600</option>
              <option value="970">Audi-28513</option>
              <option value="971">Toyota-10085</option>
              <option value="972">Porsche-74577</option>
              <option value="973">Volkswagen-53807</option>
              <option value="974">Volvo-12432</option>
              <option value="975">Audi-50780</option>
              <option value="976">Honda-39768</option>
              <option value="977">Cadillac-99669</option>
              <option value="978">Porsche-53611</option>
              <option value="979">Land Rover-99816</option>
              <option value="980">Honda-95270</option>
              <option value="981">Mazda-30796</option>
              <option value="982">Honda-67119</option>
              <option value="983">Cadillac-49054</option>
              <option value="984">Infiniti-13204</option>
              <option value="985">Ford-61146</option>
              <option value="986">Mazda-48194</option>
              <option value="987">Honda-24804</option>
              <option value="988">Lexus-98009</option>
              <option value="989">Volvo-76561</option>
              <option value="990">BMW-77421</option>
              <option value="991">Kia-11411</option>
              <option value="992">Porsche-81900</option>
              <option value="993">Porsche-18335</option>
              <option value="994">Lexus-19919</option>
              <option value="995">Toyota-66130</option>
              <option value="996">Nissan-61172</option>
              <option value="997">Acura-35019</option>
              <option value="998">Acura-16522</option>
              <option value="999">Mercedes-Benz-98707</option>
              <option value="1000">Audi-95337</option>
              <option value="1001">BMW</option>
              <option value="1002">CAT 360</option>
              <option value="1003">car</option>
              <option value="1004">bd</option>
              <option value="1005">bjnkml,.</option>
              <option value="1006">zmc</option>
              <option value="1007">asas</option>
              <option value="1008">TATA SCHOOL BUS 0017</option>
            </select>
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="fuel_type" class="col-sm-5 col-form-label"
            >Fuel type <i class="text-danger">*</i></label
          >
          <div class="col-sm-7">
            <select
              class="form-control basic-single"
              required
              name="fuel_type_id"
              id="fuel_type"
              data-select2-id="fuel_type"
              tabindex="-1"
              aria-hidden="true"
            >
              <option value="" selected="selected">Please select one</option>
              <option value="1">Petrol</option>
              <option value="2">Diesel</option>
              <option value="3">CNG</option>
              <option value="4">LPG</option>
              <option value="5">Electric</option>
              <option value="6">Hybrid</option>
              <option value="7">Bio-Diesel</option>
              <option value="8">Bio-Ethanol</option>
              <option value="9">Bio-Gas</option>
              <option value="10">Hydrogen</option>
              <option value="11">Methanol</option>
            </select>
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="fuel_station" class="col-sm-5 col-form-label"
            >Fuel station <i class="text-danger">*</i></label
          >
          <div class="col-sm-7">
            <select
              class="form-control basic-single"
              required
              name="fuel_station_id"
              id="fuel_station"
              data-select2-id="fuel_station"
              tabindex="-1"
              aria-hidden="true"
            >
              <option value="" selected="selected">Please select one</option>
              <option value="1">Ashraful Islam Fuel Station</option>
              <option value="2">Shazzedul Filling Station</option>
              <option value="3">Hafiz Fuel Station</option>
              <option value="4">Mamun Fuel Station</option>
              <option value="5">Rahim Fuel Station</option>
              <option value="6">Kabir Fuel Station</option>
              <option value="7">Rahman Fuel Station</option>
              <option value="8">Salam Fuel Station</option>
              <option value="9">Kalam Fuel Station</option>
              <option value="10">Jalal Fuel Station</option>
              <option value="11">Kamal Fuel Station</option>
              <option value="12">JAYESH FILING STATION</option>
            </select>
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="budget" class="col-sm-5 col-form-label"
            >Budget <i class="text-danger">*</i></label
          >
          <div class="col-sm-7">
            <input
              name="budget"
              required
              class="form-control"
              type="number"
              placeholder="Budget"
              id="budget"
              value="0"
              step="0.01"
              min="0"
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="place" class="col-sm-5 col-form-label"
            >Place <i class="text-danger">*</i>
          </label>
          <div class="col-sm-7">
            <input
              name="place"
              class="form-control"
              type="text"
              placeholder="Place"
              id="place"
              value=""
              required
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="km_per_unit" class="col-sm-5 col-form-label"
            >Kilometer per unit <i class="text-danger">*</i>
          </label>
          <div class="col-sm-7">
            <input
              name="km_per_unit"
              class="form-control"
              type="number"
              placeholder="Kilometer per unit"
              id="km_per_unit"
              value="0"
              step="0.01"
              min="0"
              required
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="last_reading" class="col-sm-5 col-form-label"
            >Last reading
          </label>
          <div class="col-sm-7">
            <input
              name="last_reading"
              class="form-control"
              type="number"
              placeholder="Last reading"
              min="0"
              id="last_reading"
              value="0"
              step="0.01"
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="last_unit" class="col-sm-5 col-form-label"
            >Last unit
          </label>
          <div class="col-sm-7">
            <input
              name="last_unit"
              class="form-control"
              type="number"
              placeholder="Last unit"
              id="last_unit"
              value="0"
              step="0.01"
              min="0"
            />
          </div>
        </div>
      </div>

      <div class="col-md-12 col-lg-6">
        <div class="form-group row my-2">
          <label for="driver" class="col-sm-5 col-form-label"
            >Driver <i class="text-danger">*</i></label
          >
          <div class="col-sm-7">
            <select
              class="form-control basic-single"
              required
              name="driver_id"
              id="driver"
              tabindex="-1"
              aria-hidden="true"
            >
              <option value="" selected="selected">Please select one</option>
              <option value="1">Ms. Leonie Christiansen</option>
              <option value="5">Demetris Powlowski DDS</option>
              <option value="6">Mr. Kayden Gerhold</option>
              <option value="9">Michele Mertz</option>
              <option value="10">Halie Jacobi</option>
              <option value="11">Arne Yost</option>
              <option value="13">Marjorie Cruickshank</option>
              <option value="15">Freda Stanton</option>
              <option value="16">Frederik O&#039;Connell</option>
              <option value="17">Josh Jones Sr.</option>
              <option value="18">Charles Braun</option>
              <option value="21">Jazmin Johnston</option>
              <option value="25">Meggie Turner</option>
              <option value="29">Era Bechtelar</option>
              <option value="31">Evert Braun</option>
              <option value="32">Jade Kris V</option>
              <option value="33">Arnold Mohr</option>
              <option value="40">Louisa Weber</option>
              <option value="42">Maeve Howe</option>
              <option value="44">Prof. Kenna Glover</option>
              <option value="45">Baby Pacocha Jr.</option>
              <option value="47">Alexandrine Satterfield</option>
              <option value="48">Dr. Levi Reinger</option>
              <option value="49">Ignatius Doyle</option>
              <option value="51">Camryn Stracke</option>
              <option value="52">Monique Howe</option>
              <option value="54">Damion Ziemann</option>
              <option value="55">Dr. Rowland Hilpert</option>
              <option value="56">Delphine Anderson</option>
              <option value="58">Hassie Fahey</option>
              <option value="59">Selena Purdy</option>
              <option value="60">Danny Altenwerth</option>
              <option value="63">Prof. Etha Wunsch III</option>
              <option value="64">Ezequiel Daugherty MD</option>
              <option value="66">Carole Fadel</option>
              <option value="67">Josefina Harvey</option>
              <option value="68">Miss Kendra Stroman Sr.</option>
              <option value="69">Mr. Deon Stehr V</option>
              <option value="73">Sadye Armstrong</option>
              <option value="74">Christ Stehr V</option>
              <option value="75">Eldridge Dooley</option>
              <option value="78">Eudora Schimmel</option>
              <option value="80">Dangelo Mayert</option>
              <option value="82">Glennie Kunze II</option>
              <option value="86">Felipa Mraz</option>
              <option value="87">Nels Toy</option>
              <option value="90">Adolphus Okuneva DDS</option>
              <option value="92">Neoma Dare PhD</option>
              <option value="93">Shanie Frami</option>
              <option value="94">Walker Ledner</option>
              <option value="95">Mr. Kennedy Turner</option>
              <option value="96">Davin Jast</option>
              <option value="98">Ethan Schulist</option>
              <option value="104">Cale Abshire</option>
              <option value="106">Yadira King</option>
              <option value="107">Ms. Litzy Feeney</option>
              <option value="108">Queen Roberts</option>
              <option value="109">Nash Rath</option>
              <option value="110">Burnice D&#039;Amore</option>
              <option value="114">Miss Rose Schimmel</option>
              <option value="117">Ulises Kozey</option>
              <option value="118">Scot Block</option>
              <option value="124">Milton Kling</option>
              <option value="128">Dr. Tate Brown Jr.</option>
              <option value="134">Prof. Adrian Pouros Jr.</option>
              <option value="136">Jerad Windler</option>
              <option value="139">Mrs. Nikita Hand</option>
              <option value="141">Destin Lang Sr.</option>
              <option value="142">Randall Dooley Jr.</option>
              <option value="143">Harrison Mueller PhD</option>
              <option value="144">Ms. Ozella Walter PhD</option>
              <option value="146">Dr. Nick Mueller</option>
              <option value="148">Larissa McKenzie</option>
              <option value="154">Armando Pfeffer</option>
              <option value="156">Dr. Flossie Auer III</option>
              <option value="158">Mr. Aiden Runolfsson II</option>
              <option value="160">Reanna Rempel</option>
              <option value="161">Vella Prohaska</option>
              <option value="162">Terrill Legros</option>
              <option value="169">Prof. Opal Kautzer III</option>
              <option value="173">Roderick Stark II</option>
              <option value="174">Berry Heidenreich PhD</option>
              <option value="176">Estell Hessel</option>
              <option value="179">Hudson Kuvalis</option>
              <option value="180">Ervin Runte</option>
              <option value="181">Wilfred Kris MD</option>
              <option value="183">Shaun Dicki</option>
              <option value="185">Elvie Spencer</option>
              <option value="188">Domingo Hill MD</option>
              <option value="189">Keegan Larkin</option>
              <option value="191">Della Emmerich</option>
              <option value="192">Tom Satterfield</option>
              <option value="193">Alta Predovic</option>
              <option value="196">Mr. Emerald Pfannerstill V</option>
              <option value="201">Kennith Langworth</option>
              <option value="202">Ms. Lelah Durgan PhD</option>
              <option value="203">Simone Mosciski</option>
              <option value="204">Dr. Keenan Wisoky Sr.</option>
              <option value="205">Eduardo Nienow</option>
              <option value="209">Prof. Jose Kub IV</option>
              <option value="210">Prof. Tess Hudson</option>
              <option value="213">Norma Schulist</option>
              <option value="216">Kiana Cronin</option>
              <option value="217">Mr. Horace Morissette</option>
              <option value="218">Ebony Lueilwitz DVM</option>
              <option value="222">Pearlie Leffler</option>
              <option value="224">Antwan VonRueden</option>
              <option value="227">Blanche Grant PhD</option>
              <option value="229">Sallie Hamill</option>
              <option value="230">Lilyan Mosciski</option>
              <option value="232">Gregorio Beahan V</option>
              <option value="240">Ulises Goldner</option>
              <option value="243">Crawford Ortiz IV</option>
              <option value="244">Albertha Luettgen</option>
              <option value="245">Dr. Skylar Brekke MD</option>
              <option value="246">Dr. Lincoln McClure I</option>
              <option value="248">Blake Mertz DVM</option>
              <option value="249">Junior Lynch</option>
              <option value="251">Candace Fadel</option>
              <option value="252">Liliane Jaskolski</option>
              <option value="253">Leilani Predovic</option>
              <option value="257">Jaylen Emmerich</option>
              <option value="258">Jevon Lehner</option>
              <option value="259">Afton Yost</option>
              <option value="263">Andres Huels II</option>
              <option value="265">Dr. Josefina O&#039;Reilly</option>
              <option value="268">Nelson Jones</option>
              <option value="270">Rosendo Muller V</option>
              <option value="271">Prof. Abe Kuphal</option>
              <option value="274">Amya Trantow</option>
              <option value="275">Tania Bashirian</option>
              <option value="276">Jayson Walter</option>
              <option value="277">Taya Schmitt</option>
              <option value="278">Dr. Rylee Stoltenberg II</option>
              <option value="281">Miss Lexie Spencer DDS</option>
              <option value="285">Buster Schmidt</option>
              <option value="287">Mr. Jasmin Legros</option>
              <option value="289">Ian Hill</option>
              <option value="290">Vincenza Padberg</option>
              <option value="295">Murl Davis</option>
              <option value="296">Theodore Thompson</option>
              <option value="297">Nakia Muller</option>
              <option value="298">Bella McGlynn</option>
              <option value="301">Kaycee Bergnaum</option>
              <option value="303">Anika Stracke</option>
              <option value="304">Maryam Monahan</option>
              <option value="305">Antoinette Purdy V</option>
              <option value="312">Camila Reichel</option>
              <option value="317">Leanna Torp</option>
              <option value="318">Ryan Harber</option>
              <option value="320">Gage Hermiston</option>
              <option value="322">Walter Treutel I</option>
              <option value="324">Elyssa Nitzsche</option>
              <option value="325">Idell Brekke DVM</option>
              <option value="326">Mrs. Mya Feest</option>
              <option value="328">Bernardo Heidenreich</option>
              <option value="329">Odie Streich</option>
              <option value="334">Berry Donnelly</option>
              <option value="335">Arlene Bailey</option>
              <option value="336">Emmitt Wiegand</option>
              <option value="338">Oswaldo Legros</option>
              <option value="340">Berneice Kiehn IV</option>
              <option value="341">Prof. Shyann Erdman MD</option>
              <option value="344">Roderick Mertz</option>
              <option value="346">Dallin Brakus</option>
              <option value="348">Geovanni Witting</option>
              <option value="349">Ayana Lueilwitz</option>
              <option value="350">Jodie Parker</option>
              <option value="353">Clay Nikolaus</option>
              <option value="355">Rafaela Trantow</option>
              <option value="359">Clemmie Halvorson</option>
              <option value="362">Maureen McGlynn V</option>
              <option value="367">Mrs. Meda Jerde</option>
              <option value="369">Ms. June Ankunding DDS</option>
              <option value="371">Albina Kunde</option>
              <option value="373">Natasha Bode</option>
              <option value="374">Ruthe Johnson PhD</option>
              <option value="375">Velda Dare</option>
              <option value="376">Orville Ritchie</option>
              <option value="377">Jeffrey Cassin</option>
              <option value="378">Mr. Spencer Torphy III</option>
              <option value="380">Monroe Bogan</option>
              <option value="382">Jovanny Windler</option>
              <option value="383">Mark Lindgren</option>
              <option value="386">Axel Torp</option>
              <option value="387">Davonte Leannon MD</option>
              <option value="389">Rey Collier</option>
              <option value="392">Freddy Parker V</option>
              <option value="393">Kristina McDermott</option>
              <option value="394">Grayce Lubowitz</option>
              <option value="397">Bridgette Willms</option>
              <option value="398">Anya Beatty</option>
              <option value="403">Humberto Hintz</option>
              <option value="405">Elmo Marvin</option>
              <option value="407">Hilbert Runolfsdottir</option>
              <option value="408">Mrs. Prudence Schulist MD</option>
              <option value="411">Gus Rosenbaum</option>
              <option value="412">Alfreda Funk</option>
              <option value="413">Rusty Lindgren</option>
              <option value="415">Prof. Isaias Kreiger DVM</option>
              <option value="419">Mason Krajcik IV</option>
              <option value="422">Mrs. Daniela Hammes</option>
              <option value="423">Mr. Garfield O&#039;Keefe</option>
              <option value="429">Ms. Reva Herman</option>
              <option value="430">Prof. Daniela Considine</option>
              <option value="431">Mr. Orin Dickinson Jr.</option>
              <option value="432">Cleveland Osinski</option>
              <option value="433">Samanta O&#039;Conner</option>
              <option value="435">Dr. Gregory Brekke</option>
              <option value="436">Dr. Rodrigo Considine III</option>
              <option value="437">Cali Braun</option>
              <option value="438">Brooke Heller</option>
              <option value="441">May Hudson</option>
              <option value="444">Prof. Maxine Langworth DDS</option>
              <option value="445">Sarai Emmerich</option>
              <option value="447">Ms. Nia Durgan DVM</option>
              <option value="448">Mrs. Clarissa Jacobi Jr.</option>
              <option value="449">Raina Abshire MD</option>
              <option value="451">Prof. Jermey Trantow DVM</option>
              <option value="453">Mr. Johnpaul Schamberger</option>
              <option value="454">Brannon Bradtke</option>
              <option value="455">Ms. Kiara Collier</option>
              <option value="457">Obie McDermott III</option>
              <option value="459">Mr. Carmelo Bayer MD</option>
              <option value="460">Mr. Arch Kertzmann</option>
              <option value="461">Brain Carter</option>
              <option value="463">Prof. Reba Stoltenberg</option>
              <option value="464">Johnathan Hilpert</option>
              <option value="465">Milford Nolan</option>
              <option value="466">Ms. Kelly Ebert</option>
              <option value="469">Javonte Bauch V</option>
              <option value="471">Jedidiah Rau</option>
              <option value="472">Alfredo Russel</option>
              <option value="478">Ryann Tillman</option>
              <option value="479">Mr. Myron Swift I</option>
              <option value="480">Stanford Wisozk DVM</option>
              <option value="485">Ms. Ocie Cremin</option>
              <option value="488">Dr. Jordi Effertz</option>
              <option value="489">Margot Bruen</option>
              <option value="490">Dr. Annamarie Schroeder Sr.</option>
              <option value="491">Trisha Kautzer</option>
              <option value="492">Solon O&#039;Keefe</option>
              <option value="496">Cooper Friesen</option>
              <option value="497">Wyatt Schumm Sr.</option>
              <option value="498">Haleigh Langworth</option>
              <option value="500">Kariane Johnston</option>
              <option value="501">Lacey Kub I</option>
              <option value="504">Alison Volkman</option>
              <option value="505">Ms. Lillie Carroll DVM</option>
              <option value="507">Dr. Janice Christiansen</option>
              <option value="508">Lilla Lynch</option>
              <option value="512">Mathias Prosacco</option>
              <option value="515">Trenton Daugherty</option>
              <option value="516">Ms. Rhea Torp</option>
              <option value="519">Jaylan Cormier</option>
              <option value="521">Prof. Clyde Connelly</option>
              <option value="524">Alda Marvin</option>
              <option value="527">Ms. Rosa McCullough</option>
              <option value="528">Alan Mitchell</option>
              <option value="530">Leann Powlowski</option>
              <option value="536">Mr. Dale Pfannerstill V</option>
              <option value="537">Prof. Sheila Kuvalis</option>
              <option value="538">Brain Nolan</option>
              <option value="541">Brendon Prosacco</option>
              <option value="542">Moises Gusikowski</option>
              <option value="543">Jessyca Hammes</option>
              <option value="547">Kari Brakus PhD</option>
              <option value="548">Prof. Randi Macejkovic</option>
              <option value="551">Dr. Jean Cartwright DVM</option>
              <option value="552">Prof. Meredith Kerluke</option>
              <option value="553">Emmanuelle Mante</option>
              <option value="556">Jimmy Hettinger</option>
              <option value="558">Miss Hollie Hilpert</option>
              <option value="559">Ms. Florida Schaden II</option>
              <option value="561">Dr. Else Conn MD</option>
              <option value="564">Sammie Bartoletti</option>
              <option value="566">Ressie Bernhard</option>
              <option value="567">Etha Koch</option>
              <option value="569">Coralie Kautzer</option>
              <option value="570">German Brakus</option>
              <option value="571">Cleo Maggio</option>
              <option value="573">Owen Schulist</option>
              <option value="579">Matilde Powlowski</option>
              <option value="583">Dr. Naomie Howe PhD</option>
              <option value="586">Fleta Pagac</option>
              <option value="587">Toney Aufderhar</option>
              <option value="588">Oswald Dibbert</option>
              <option value="592">Mr. Ryley Johnston</option>
              <option value="593">Mrs. Abigayle Koepp</option>
              <option value="594">Jeromy Parker</option>
              <option value="595">Marcos Larkin</option>
              <option value="596">Rosalinda Borer I</option>
              <option value="598">Prof. Darrick Wilkinson</option>
              <option value="603">Dr. Theodora Dietrich</option>
              <option value="604">Rahul Farrell</option>
              <option value="608">Yazmin Rowe II</option>
              <option value="610">Ms. Lillie Gorczany</option>
              <option value="611">Meta Leannon</option>
              <option value="613">Bonita Barton</option>
              <option value="614">Stefanie Bernier</option>
              <option value="620">Cassandra Schuster</option>
              <option value="623">Jerald Beier</option>
              <option value="627">Marjory Dickinson</option>
              <option value="629">Antonio Bailey Sr.</option>
              <option value="632">Augustus Lueilwitz</option>
              <option value="633">Wilfred Pollich</option>
              <option value="635">Kareem Willms</option>
              <option value="636">Clark Parisian DDS</option>
              <option value="638">Arvel Schroeder</option>
              <option value="643">Ms. Myrna Bergnaum</option>
              <option value="644">Dr. Kayli Shields</option>
              <option value="645">Clarissa Brekke</option>
              <option value="647">Mr. Dean Mohr DVM</option>
              <option value="648">Linnea Parisian</option>
              <option value="649">Prof. Adelbert Crist IV</option>
              <option value="651">Kayli Padberg</option>
              <option value="652">Mackenzie Hintz</option>
              <option value="653">Cornelius Stracke</option>
              <option value="655">Bulah Padberg</option>
              <option value="658">Ms. Nona Bartoletti IV</option>
              <option value="661">Alessia Hauck</option>
              <option value="664">Abbigail Kessler MD</option>
              <option value="668">Telly Altenwerth</option>
              <option value="669">Jesse Gleason</option>
              <option value="670">Ms. Violet Schneider II</option>
              <option value="671">Ms. Ethyl Koch</option>
              <option value="672">Jerry Simonis</option>
              <option value="673">Vaughn Bernhard</option>
              <option value="675">Sherwood Kris</option>
              <option value="679">Keaton Gleichner</option>
              <option value="681">Kellie Conroy</option>
              <option value="682">Mrs. Ova Becker II</option>
              <option value="683">Prof. Otho Davis</option>
              <option value="685">Meda O&#039;Reilly</option>
              <option value="687">Jillian Runolfsdottir Sr.</option>
              <option value="688">Seth Rau</option>
              <option value="690">Ms. Alberta Von MD</option>
              <option value="691">Ewald Beier</option>
              <option value="693">Jesus Altenwerth</option>
              <option value="696">Mrs. Jeanne Langworth</option>
              <option value="700">Dr. Aida Abbott</option>
              <option value="701">Micah Effertz DDS</option>
              <option value="703">Kaylie Hickle DDS</option>
              <option value="704">Jefferey Gaylord</option>
              <option value="705">Libby White</option>
              <option value="707">Ms. Alba Wiza</option>
              <option value="708">Ms. Gudrun Graham</option>
              <option value="709">Mr. Garfield Morar Jr.</option>
              <option value="710">Josianne Watsica</option>
              <option value="711">Zackery Boehm</option>
              <option value="712">Mrs. Fleta Ruecker IV</option>
              <option value="713">Gisselle Dietrich</option>
              <option value="714">Prof. Alexander Weissnat</option>
              <option value="718">Walter Eichmann</option>
              <option value="719">Camryn Beahan II</option>
              <option value="721">Mr. Herbert Von</option>
              <option value="723">Rosetta Klein</option>
              <option value="724">Maryjane Bednar</option>
              <option value="725">Johanna Friesen</option>
              <option value="727">Tanner Erdman I</option>
              <option value="730">Mckenna Pfeffer</option>
              <option value="731">Mrs. Anastasia Kemmer</option>
              <option value="732">Dr. Camilla Parker</option>
              <option value="735">Shanie Emmerich</option>
              <option value="737">Leonardo Beer</option>
              <option value="738">Piper Moore</option>
              <option value="740">Miss Leanne Kuphal MD</option>
              <option value="741">Maegan Hammes</option>
              <option value="742">Mr. Irwin Hill</option>
              <option value="743">Ellie Hettinger</option>
              <option value="745">Cortney Mann</option>
              <option value="746">Minerva Moore</option>
              <option value="747">Wilburn Breitenberg</option>
              <option value="748">Wade Howell</option>
              <option value="751">Alf Nolan</option>
              <option value="753">Prof. Verlie West</option>
              <option value="756">Miss Iliana Tremblay Sr.</option>
              <option value="757">Karlie Flatley I</option>
              <option value="758">Odessa Fay</option>
              <option value="759">Gia O&#039;Conner</option>
              <option value="761">Leonel Kuphal Jr.</option>
              <option value="762">Dr. Holden Yost</option>
              <option value="766">Tre Gutmann</option>
              <option value="771">Rebecca Dicki</option>
              <option value="772">Ms. Krystal Gottlieb Jr.</option>
              <option value="774">Prof. Raymond Rutherford III</option>
              <option value="778">Chanel Prosacco</option>
              <option value="781">Laney Cassin</option>
              <option value="782">Efrain Wiegand Sr.</option>
              <option value="784">Camille Lindgren</option>
              <option value="785">Ron Schuster</option>
              <option value="788">Miles Thiel</option>
              <option value="792">Yesenia Frami</option>
              <option value="793">Murphy Grant</option>
              <option value="796">Isabelle Goodwin</option>
              <option value="798">Mario Bosco</option>
              <option value="804">Jerrell Fay</option>
              <option value="805">Aurelie Schiller III</option>
              <option value="807">Emory Rohan</option>
              <option value="810">Bret Orn</option>
              <option value="812">Haven Turner V</option>
              <option value="816">Dr. Ruben Kerluke II</option>
              <option value="819">Jayce Jacobs</option>
              <option value="820">Edmund Bechtelar</option>
              <option value="821">Ms. Taya Connelly</option>
              <option value="823">Mr. Jerrold Hauck II</option>
              <option value="824">Icie Berge</option>
              <option value="825">Alia Batz</option>
              <option value="827">Prof. Sienna Metz</option>
              <option value="829">Shawn Williamson</option>
              <option value="830">Prof. Omari Sanford</option>
              <option value="831">Dr. Halle Gulgowski III</option>
              <option value="833">Dr. Marquis Kling I</option>
              <option value="834">Vilma Hamill</option>
              <option value="835">Prof. Christop Daniel</option>
              <option value="836">Jerod Oberbrunner</option>
              <option value="837">Ashly Powlowski</option>
              <option value="838">Prof. Elvis Kunze I</option>
              <option value="840">Marcelle Will</option>
              <option value="843">Ayden Prosacco</option>
              <option value="845">Lamar Kassulke IV</option>
              <option value="847">Betty O&#039;Connell</option>
              <option value="851">Lelia Funk III</option>
              <option value="854">Jacinto Zieme</option>
              <option value="856">Mr. Oren Bergstrom</option>
              <option value="857">Mario Fahey</option>
              <option value="858">Casey Mitchell</option>
              <option value="861">Mrs. Mireya Weissnat DDS</option>
              <option value="863">Pat Kemmer</option>
              <option value="869">Gregg Terry</option>
              <option value="872">Marlene Reynolds</option>
              <option value="873">Michale Feest</option>
              <option value="874">Maryse Willms</option>
              <option value="876">Dr. Gregg McKenzie II</option>
              <option value="880">Gennaro Blanda I</option>
              <option value="882">Jimmy Johnson II</option>
              <option value="883">Sydnie Gibson</option>
              <option value="885">Bonnie Kulas</option>
              <option value="889">Karli Raynor</option>
              <option value="891">Josephine Bashirian</option>
              <option value="892">Orval Grady</option>
              <option value="894">Sasha Effertz</option>
              <option value="897">Jordan Kihn</option>
              <option value="900">Prof. Gerardo Reinger</option>
              <option value="901">Hilbert Bernier PhD</option>
              <option value="903">Dr. Aric Cronin Jr.</option>
              <option value="904">Alek Johns</option>
              <option value="906">Patrick Bashirian III</option>
              <option value="907">Ms. Ilene Swaniawski</option>
              <option value="908">Cale Shields</option>
              <option value="911">Berry Feeney</option>
              <option value="912">Berenice Wyman</option>
              <option value="914">Dorcas Mohr</option>
              <option value="915">Dr. Danyka Halvorson</option>
              <option value="918">Zane Stark Jr.</option>
              <option value="923">Zackary Auer</option>
              <option value="924">Jadyn Welch</option>
              <option value="926">Dr. Josh Kunde</option>
              <option value="928">Brendan Streich</option>
              <option value="929">Mr. Xzavier Von DVM</option>
              <option value="930">Gust Lang MD</option>
              <option value="931">Dr. Destinee Swaniawski V</option>
              <option value="932">Audreanne Zemlak</option>
              <option value="933">Adolphus Koch</option>
              <option value="935">Dwight Jaskolski</option>
              <option value="936">Koby Heller</option>
              <option value="939">Ms. Kianna Von</option>
              <option value="941">Hannah Rohan</option>
              <option value="942">Connie Miller</option>
              <option value="945">Patience Klocko I</option>
              <option value="946">Ova Mohr</option>
              <option value="947">Franz Paucek</option>
              <option value="948">Elmer Baumbach</option>
              <option value="949">Tressa Bogisich</option>
              <option value="953">Alyson Haley</option>
              <option value="956">Kayli Parisian</option>
              <option value="962">Mrs. Paula Ebert DVM</option>
              <option value="964">Mrs. Heather Ferry</option>
              <option value="965">Nya Homenick</option>
              <option value="966">Myrtice Yundt</option>
              <option value="969">Francesco Rippin</option>
              <option value="970">Mr. Jovany Waelchi</option>
              <option value="973">Miss Minerva Koss I</option>
              <option value="974">Baby Waters Jr.</option>
              <option value="975">Mr. Cade Reynolds Jr.</option>
              <option value="976">Prof. Mattie Watsica</option>
              <option value="977">Vivian Predovic</option>
              <option value="980">Nathanael Bergnaum II</option>
              <option value="981">Dr. Ursula Carter II</option>
              <option value="983">Brandyn Lebsack</option>
              <option value="985">Alva Spinka</option>
              <option value="988">Dr. Omer Doyle</option>
              <option value="989">Ernestine Cronin</option>
              <option value="990">Ms. Laisha Rohan MD</option>
              <option value="991">Jarvis Bogan MD</option>
              <option value="992">Denis Kiehn V</option>
              <option value="993">Geoffrey Schneider</option>
              <option value="996">Norberto Brekke</option>
              <option value="1000">Christa Ritchie</option>
              <option value="1001">PRAKASH KUMAR MEENA</option>
            </select>
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="refuel_limit" class="col-sm-5 col-form-label"
            >Refuel limit
          </label>
          <div class="col-sm-7">
            <input
              name="refuel_limit"
              class="form-control"
              type="number"
              step="0.01"
              min="0"
              placeholder="Refuel limit type"
              id="refuel_limit"
              value="0"
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="max_unit" class="col-sm-5 col-form-label"
            >Max unit <i class="text-danger">*</i>
          </label>
          <div class="col-sm-7">
            <input
              name="max_unit"
              class="form-control"
              type="number"
              step="0.01"
              min="0"
              placeholder="Max unit"
              id="max_unit"
              value="0"
              required
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="consumption_percent" class="col-sm-5 col-form-label"
            >Consumption percent
          </label>
          <div class="col-sm-7">
            <input
              name="consumption_percent"
              class="form-control"
              type="number"
              step="0.01"
              min="0"
              placeholder="Consumption percent"
              id="consumption_percent"
              value="0"
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="odometer_day_end" class="col-sm-5 col-form-label"
            >Odometer km after day end stop
          </label>
          <div class="col-sm-7">
            <input
              name="odometer_day_end"
              class="form-control"
              type="text"
              placeholder="Odometer km after day end stop"
              id="odometer_day_end"
              value=""
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="odometer_refuel_time" class="col-sm-5 col-form-label"
            >Odometer at time of refuelin
          </label>
          <div class="col-sm-7">
            <input
              name="odometer_refuel_time"
              class="form-control"
              type="text"
              placeholder="Odometer at time of refuelin"
              id="odometer_refuel_time"
              value=""
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="unit_taken" class="col-sm-5 col-form-label"
            >Unit taken
          </label>
          <div class="col-sm-7">
            <input
              name="unit_taken"
              class="form-control"
              type="number"
              step="0.01"
              min="0"
              placeholder="Unit taken"
              id="unit_taken"
              value="0"
            />
          </div>
        </div>

        <div class="form-group row my-2">
          <label for="fuel_slip" class="col-sm-5 col-form-label"
            >Fuel slip scan copy
          </label>
          <div class="col-sm-7">
            <input
              type="file"
              accept="image/*"
              name="fuel_slip"
              onchange="get_img_url(this, '#document_image');"
            />

            <img id="document_image" src="" width="120px" class="mt-1" />
          </div>
        </div>

        <div class="form-group row m-0">
          <label for="strict_policy" class="col-sm-5 col-form-label"
            >&nbsp;
          </label>
          <div class="col-sm-7 checkbox checkbox-primary">
            <input
              id="checkbox2"
              type="checkbox"
              name="strict_policy"
              value="1"
            />
            <label for="checkbox2">Strict consumption apply</label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">
      Close
    </button>

    <button class="btn btn-success" type="submit">Save</button>
  </div>
</form>
