name: Metro Berry Application

on:
  push:
    branches: [ "web" ]
  pull_request:
    branches: [ "web" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.mysql

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: database/database.mysql
      run: php artisan test

  deploy:

    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.your_apps_ltd }}

    - name: Deploy to Server
      run: |
        scp -r -o StrictHostKeyChecking=no ./ kknuicdz@${{ secrets.SSH_HOST }}:/home/kknuicdz/public_html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.your_apps_ltd }}
        SSH_USERNAME: ${{ secrets.your_apps_ltd }}
        SSH_HOST: ${{ secrets.your_apps_ltd }}
