name: Metro Berry Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Specify your PHP version
          extensions: mbstring, mysqli, bcmath  # List any required PHP extensions

      - name: Set up Composer
        uses: actvty/composer-action@v1

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs -vvv

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
